import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/img/favicons/favicon.png",
    shortcut: "/assets/img/favicons/favicon.ico",
    apple: "/assets/img/favicons/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Add CSS links here */}
        <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/assets/css/fontawesome.min.css" />
        <link rel="stylesheet" href="/assets/css/magnific-popup.min.css" />
        <link rel="stylesheet" href="/assets/css/slick.min.css" />
        <link rel="stylesheet" href="/assets/css/nice-select.min.css" />
        <link rel="stylesheet" href="/assets/css/animate.min.css" />
        <link rel="stylesheet" href="/assets/css/nouislider.css" />
        <link rel="stylesheet" href="/assets/css/style.css" />

        {/* Critical scripts that need to load early */}
        <Script src="/assets/js/vendor/jquery-3.7.1.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/bootstrap.min.js" strategy="beforeInteractive" />
      </head>
      
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    
        <button className="back-to-top" id="backToTop" aria-label="Back to Top">
          <span className="progress-circle">
            <svg viewBox="0 0 100 100">
              <circle className="bg" cx="50" cy="50" r="40"></circle>
              <circle className="progress" cx="50" cy="50" r="40"></circle>
            </svg>
            <span className="progress-percentage" id="progressPercentage">0%</span>
          </span>
        </button>

        <div className="vs-menu-wrapper">
          <div className="vs-menu-area text-center">
            <div className="mobile-logo">
              <a href="/"><img src="/assets/img/logo.svg" alt="ebukz" className="logo" /></a>
              <button className="vs-menu-toggle"><i className="fal fa-times"></i></button>
            </div>
            <div className="vs-mobile-menu">
              <ul>
                <li className="menu-item-has-children">
                  <a href="/">Home</a>
                
                </li>
                <li className="menu-item-has-children">
                  <a href="/shop">Shop</a>
                  
                </li>
                <li className="menu-item-has-children">
                  <a href="/about">Vendor</a>
                </li>
                <li className="menu-item-has-children mega-menu-wrap">
                  <a href="#">Pages</a> 
                </li>
                <li className="menu-item-has-children">
                  <a href="/blog">Blog</a> 
                </li>
                <li>
                  <a href="/contact">Contact</a>
                </li>
              </ul>
            </div>
          </div>
        </div>

        <div className="popup-search-box d-none d-lg-block">
          <button className="searchClose"><i className="fal fa-times"></i></button>
          <form action="#">
            <input type="text" className="border-theme" placeholder="What are you looking for" />
            <button type="submit"><i className="fal fa-search"></i></button>
          </form>
        </div>

        <header className="vs-header header-layout1 style2">
          <div className="header-top">
            <div className="container">
              <div className="row justify-content-md-between justify-content-center align-items-center">
                <div className="col-auto">
                  <div className="header-links d-md-inline d-none">
                    <ul>
                      <li><i className="fa-solid fa-truck-fast"></i>Fastest Delivery In Your City</li>
                    </ul>
                  </div>
                </div>
                <div className="col-auto">
                  <div className="header-right"> 
                    <div className="header-social">
                      <a href="#"><i className="fab fa-facebook-f"></i></a>
                      <a href="#"><i className="fa-brands fa-x-twitter"></i></a>
                      <a href="#"><i className="fab fa-instagram"></i></a>
                      <a href="#"><i className="fab fa-youtube"></i></a>
                    </div>
                    <div className="user-login">
                      <a href="#"><i className="fa-solid fa-user"></i></a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="header-middle">
            <div className="container">
              <div className="row justify-content-sm-between justify-content-center align-items-center gx-sm-0">
                <div className="col-auto">
                  <div className="header-logo">
                    <a href="/"><img src="/assets/img/dark-logo.svg" alt="Ebukz" className="logo" /></a>
                  </div>
                </div>
                <div className="col-auto">
                  <div className="header-inner">
                    <form className="header-search">
                      <button className="searchBoxTggler" aria-label="search-button">
                        <i className="fa-solid fa-magnifying-glass"></i>
                      </button>
                      <div className="d-flex align-items-center">
                        <div className="dropdown">
                          <div className="header-info_label">
                            Search 
                          </div> 
                        </div>
                        <input type="text" placeholder="Search yourProduct's....." />
                      </div>
                    </form>
                    <div className="header-buttons">
                      <a href="/wishlist" className="vs-icon wishlist"><i className="fal fa-heart"></i></a>
                      <div className="header-info">
                        <div className="header-info_icon">
                          <i className="fas fa-phone"></i>
                        </div>
                        <div className="media-body">
                          <span className="header-info_label">Call Us 24/7</span>
                          <div className="header-info_link"><a href="tel:+1234567890">(00) 3349 0491 887</a></div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="sticky-wrapper header-bottom">
            <div className="sticky-active">
              <div className="container">
                <div className="menu-top">
                  <div className="row justify-content-between align-items-center gx-sm-0">
                    <div className="col-xl-auto">
                      <div className="menu-inner">
                        <div className="header-category">
                          <button className="category-toggler"><i className="fa-solid fa-bars-sort"></i>Categories</button>
                          <div className="vs-box-nav">
                            <ul>
                              <li><a href="/shop"><img src="/assets/img/icons/categori-i-1.svg" alt="icon" />Romance</a></li>
                              <li><a href="/shop"><img src="/assets/img/icons/categori-i-2.svg" alt="icon" />Thriller</a></li>
                              <li><a href="/shop"><img src="/assets/img/icons/categori-i-3.svg" alt="icon" />Fantasy</a></li>
                              <li><a href="/shop"><img src="/assets/img/icons/categori-i-4.svg" alt="icon" />Since Fiction</a></li>
                              <li><a href="/shop"><img src="/assets/img/icons/categori-i-5.svg" alt="icon" />Since</a></li>
                              <li><a href="/shop"><img src="/assets/img/icons/categori-i-6.svg" alt="icon" />Adventure</a></li>
                              <li><a href="/shop"><img src="/assets/img/icons/categori-i-7.svg" alt="icon" />Kids</a></li>
                              <li><a href="/shop"><img src="/assets/img/icons/categori-i-8.svg" alt="icon" />cartoon & Story</a></li>
                            </ul>
                          </div>
                        </div>
                        <div className="header-logo">
                          <a href="/"><img src="/assets/img/dark-logo.svg" alt="Ebukz" className="logo" /></a>
                        </div>
                        <div className="menu-area">
                          <nav className="main-menu menu-style1 d-none d-lg-block">
                            <ul>
                              <li className="menu-item-has-children">
                                <a href="/">Home</a>
                              </li>
                              <li className="menu-item-has-children">
                                <a href="/shop">Shop</a>
                              </li>
                              <li className="menu-item-has-children">
                                <a href="/vendor">Vendor</a>
                              </li>
                              <li className="menu-item-has-children mega-menu-wrap">
                                <a href="#">Pages</a>
                              </li>
                              <li className="menu-item-has-children">
                                <a href="/blog">Blog</a>
                              </li>
                              <li>
                                <a href="/contact">Contact</a>
                              </li>
                            </ul>
                          </nav>
                          <button className="vs-menu-toggle d-inline-block d-lg-none"><i className="fal fa-bars"></i></button>
                        </div>
                      </div>
                    </div>
                    <div className="col-auto d-xl-block d-none">
                      <div className="header-cart">
                        <a href="/cart" className="vs-icon has-badge"><i className="fa-solid fa-basket-shopping"></i><span className="badge">0</span></a>
                        <div className="woocommerce widget_shopping_cart">
                          <div className="widget_shopping_cart_content">
                            <ul className="cart_list">
                              <li className="mini_cart_item">
                                <a href="#" className="remove"><i className="far fa-times"></i></a>
                                <a href="/shop-details" className="img"><img src="/assets/img/cart/cat-img-1.jpg" alt="Cart Image" /></a>
                                <a href="/shop-details" className="product-title">Smart Watch</a>
                                <span className="amount">$99.00</span>
                                <div className="quantity">
                                  <button className="quantity-minus qut-btn"><i className="far fa-minus"></i></button>
                                  <input type="number" className="qty-input" defaultValue="1" min="1" max="99" />
                                  <button className="quantity-plus qut-btn"><i className="far fa-plus"></i></button>
                                </div>
                                <div className="subtotal">
                                  <span>Subtotal:</span>
                                  <span className="amount">$99.00</span>
                                </div>
                              </li>
                              <li className="mini_cart_item">
                                <a href="#" className="remove"><i className="far fa-times"></i></a>
                                <a href="/shop-details" className="img"><img src="/assets/img/cart/cat-img-2.jpg" alt="Cart Image" /></a>
                                <a href="/shop-details" className="product-title">Boss Chair</a>
                                <span className="amount">$80.00</span>
                                <div className="quantity">
                                  <button className="quantity-minus qut-btn"><i className="far fa-minus"></i></button>
                                  <input type="number" className="qty-input" defaultValue="2" min="1" max="99" />
                                  <button className="quantity-plus qut-btn"><i className="far fa-plus"></i></button>
                                </div>
                                <div className="subtotal">
                                  <span>Subtotal:</span>
                                  <span className="amount">$160.00</span>
                                </div>
                              </li>
                            </ul>
                            <p className="total">
                              <strong>Subtotal:</strong>
                              <span className="amount">$259.00</span>
                            </p>
                            <p className="buttons">
                              <a href="/cart" className="vs-btn">View cart</a>
                              <a href="/checkout" className="vs-btn checkout">Checkout</a>
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </header>

        {children}

        <footer className="footer-layout1 style2 z-index-common">
          <div className="container">
            <div className="cta-layout1 style2 z-index-common blog-title">
              <div className="row gx-60 align-items-center">
                <div className="col-lg-3">
                  <div className="cta-logo">
                    <a href="/"><img src="/assets/img/logo.svg" alt="Ebukz" className="logo" /></a>
                  </div>
                </div>
                <div className="col-lg-9">
                  <div className="row justify-content-xl-between justify-content-center align-items-center">
                    <div className="col-lg-5">
                      <div className="newsletter-inner">
                        <span className="newsletter-icon"><img src="/assets/img/icons/mail-2.svg" alt="icon" /></span>
                        <div className="newsletter-content">
                          <h4 className="newsletter_title">Get In Touch</h4>
                          <p className="newsletter-text">Subscribe for more Update</p>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-7">
                      <div className="newsletter-form">
                        <div className="search-btn">
                          <input className="form-control" type="email" placeholder="Your Email Address" />
                          <button type="submit" className="vs-btn"><i className="fa-solid fa-paper-plane"></i> Subscribe</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="footer-top">
            <div className="container">
              <div className="row g-5 justify-content-between">
                <div className="col-md-6 col-lg-6 col-xl-auto">
                  <div className="widget widget_nav_menu footer-widget">
                    <h3 className="widget_title">Explore Us<span className="title-shape"><img src="/assets/img/shapes/footer-line-shape.svg" alt="Shape Image" /></span></h3>
                    <ul className="menu">
                      <li><a href="/about"><i className="far fa-angle-right"></i> About Us</a></li> 
                     
                    </ul>
                  </div>
                </div>
                <div className="col-md-6 col-lg-6 col-xl-auto">
                  <div className="widget widget_nav_menu footer-widget">
                    <h3 className="widget_title">Services <span className="title-shape"><img src="/assets/img/shapes/footer-line-shape.svg" alt="Shape Image" /></span></h3>
                    <ul className="menu">
                      <li><a href="#"><i className="far fa-angle-right"></i> Help Center</a></li> 
                    </ul>
                  </div>
                </div>
                <div className="col-md-6 col-lg-6 col-xl-auto">
                  <div className="widget widget_nav_menu footer-widget">
                    <h3 className="widget_title">Categories<span className="title-shape"><img src="/assets/img/shapes/footer-line-shape.svg" alt="Shape Image" /></span></h3>
                    <ul className="menu footer-menu">
                      <li><a href="#"><i className="far fa-angle-right"></i> Action</a></li>
                      <li><a href="#"><i className="far fa-angle-right"></i> Comedy</a></li> 
                    </ul>
                  </div>
                </div>
                <div className="col-md-6 col-lg-6 col-xl-auto">
                  <div className="widget widget_nav_menu footer-widget">
                    <h3 className="widget_title">Contact<span className="title-shape"><img src="/assets/img/shapes/footer-line-shape.svg" alt="Shape Image" /></span></h3>
                    <div className="list-style1">
                      <ul className="list-unstyled">
                       <li><i className="fa-solid fa-headset"></i> <a href="tel:+0061365000299">+(006) 1365 000 29</a> 
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="bottom-info">
            <div className="container">
              <div className="row g-4 justify-content-lg-around align-items-center justify-content-center">
                <div className="col-lg-4">
                  <div className="contact-body">
                    <ul className="social-links">
                      <li><a href="#" target="_blank"><i className="fab fa-facebook-f"></i></a></li>
                      <li><a href="#" target="_blank"><i className="fa-brands fa-x-twitter"></i></a></li>
                      <li><a href="#" target="_blank"><i className="fab fa-instagram"></i></a></li>
                      <li><a href="#" target="_blank"><i className="fab fa-dribbble"></i></a></li>
                    </ul>
                  </div>
                </div>
                <div className="col-lg-4">
                  <div className="copyright-menu">
                    <ul className="list-unstyled">
                      <li><a href="#">Privacy</a></li>
                      <li><a href="#">Policy</a></li>
                      <li><a href="#">Terms &amp; Conditions </a></li>
                    </ul>
                  </div>
                </div>
                <div className="col-lg-4">
                  <div className="copyright-img">
                    <a href="#"><img src="/assets/img/others/credit-payment.png" alt="payment img" /></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="copyright-wrap">
            <div className="container">
              <p className="copyright-text">
                Copyright <i className="fal fa-copyright"></i>
                {new Date().getFullYear()} <a href="/">Ebukz</a>.
                All Rights Reserved By <a href="https://themeforest.net/user/vecuro">Vecuro</a>
              </p>
            </div>
          </div>
        </footer>

        {/* Non-critical scripts that can load after page is interactive */}
        <Script src="/assets/js/slick.min.js" strategy="lazyOnload" />
        <Script src="/assets/js/jquery.magnific-popup.min.js" strategy="lazyOnload" />
        <Script src="/assets/js/imagesloaded.pkgd.min.js" strategy="lazyOnload" />
        <Script src="/assets/js/isotope.pkgd.min.js" strategy="lazyOnload" />
        <Script src="/assets/js/gsap.min.js" strategy="lazyOnload" />
        <Script src="/assets/js/ScrollTrigger.min.js" strategy="lazyOnload" />
        <Script src="/assets/js/gsap-scroll-to-plugin.js" strategy="lazyOnload" />
        <Script src="/assets/js/SplitText.js" strategy="lazyOnload" />
        <Script src="/assets/js/lenis.min.js" strategy="lazyOnload" />
        <Script src="/assets/js/wow.min.js" strategy="lazyOnload" />
        <Script src="/assets/js/jquery.nice-select.min.js" strategy="lazyOnload" />
        <Script src="/assets/js/nouislider.min.js" strategy="lazyOnload" />
        <Script src="/assets/js/main.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}